apiVersion: jenkins.io/v1
kind: App
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  exposedServices:
  - {{ template  "fullname" . }}